checksum:
  name_template: "{{ .ArtifactName }}.{{ .Algorithm }}"
  algorithm: sha256
  split: true
builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
brews:
  - repository:
      owner: noobcollective
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/noobcollective/reme
    description: Setup up reminders easily in your terminal.
    license: MIT
    dependencies:
      - name: go
